#include "meios/completion/emitters.h"

#include "completion_detail.h"

#include <string>
#include <ostream>
#include <sstream>

namespace meios
{

namespace
{

std::string verb_name_list(const completion_model &model)
{
    std::string list;
    for(const completion_verb &verb : model.verbs)
    {
        if(!list.empty())
            list += ' ';
        list += verb.name;
    }
    return list;
}

void bash_header(std::ostream &out, const completion_model &model)
{
    out << "# " << model.program << " bash completion. Generated by `"
        << model.program << " completion bash`; do not edit.\n"
        << "# Commands:\n";
    for(const completion_verb &verb : model.verbs)
        out << "#   " << verb.name << " - " << verb.description << "\n";
}

void bash_prelude(std::ostream &out, const completion_model &model)
{
    out << "_" << model.program << "() {\n"
        << "    local cur words cword\n"
        << "    cur=\"${COMP_WORDS[COMP_CWORD]}\"\n"
        << "    words=(\"${COMP_WORDS[@]}\")\n"
        << "    cword=\"${COMP_CWORD}\"\n"
        << "    if [ \"${cword}\" -eq 1 ]; then\n"
        << "        COMPREPLY=($(compgen -W \"" << verb_name_list(model) << "\" -- \"${cur}\"))\n"
        << "        return\n"
        << "    fi\n"
        << "    local verb=\"${words[1]}\"\n"
        << "    if [ \"${verb}\" = \"completion\" ] && [ \"${cword}\" -eq 2 ]; then\n"
        << "        COMPREPLY=($(compgen -W \"" << detail::supported_shells() << "\" -- \"${cur}\"))\n"
        << "        return\n"
        << "    fi\n";
}

void bash_flag_and_dynamic(std::ostream &out, const completion_model &model)
{
    out << "    if [ \"${cur#-}\" != \"${cur}\" ]; then\n"
        << "        COMPREPLY=($(compgen -W \"$(_" << model.program << "_flags \"${verb}\")\" -- \"${cur}\"))\n"
        << "        return\n"
        << "    fi\n"
        << "    local candidate candidates=()\n"
        << "    while IFS= read -r candidate; do\n"
        << "        candidates+=(\"${candidate}\")\n"
        << "    done < <(" << model.program << " __complete \"${words[@]:1:${cword}-1}\" -- \"${cur}\")\n"
        << "    COMPREPLY=()\n"
        << "    for candidate in \"${candidates[@]}\"; do\n"
        << "        if [ -z \"${cur}\" ] || [ \"${candidate#\"${cur}\"}\" != \"${candidate}\" ]; then\n"
        << "            COMPREPLY+=(\"${candidate}\")\n"
        << "        fi\n"
        << "    done\n"
        << "}\n";
}

void bash_flags_function(std::ostream &out, const completion_model &model)
{
    out << "_" << model.program << "_flags() {\n    case \"$1\" in\n";
    for(const completion_verb &verb : model.verbs)
    {
        out << "        " << verb.name << ") printf '%s\\n' \"";
        bool first = true;
        for(const completion_option &opt : verb.options)
        {
            out << (first ? "" : " ") << opt.token;
            first = false;
        }
        out << "\" ;;\n";
    }
    out << "    esac\n}\n";
}

}

std::string emit_bash(const completion_model &model)
{
    std::ostringstream out;
    bash_header(out, model);
    bash_prelude(out, model);
    bash_flag_and_dynamic(out, model);
    bash_flags_function(out, model);
    out << "complete -F _" << model.program << " " << model.program << "\n";
    return out.str();
}

}
