#include "meios/completion/emitters.h"

#include "completion_detail.h"

#include <string>
#include <ostream>
#include <sstream>

namespace meios
{

namespace
{

bool has_dynamic_argument(const completion_verb &verb)
{
    for(const completion_argument &arg : verb.arguments)
        if(arg.dynamic)
            return true;
    return false;
}

void fish_header_and_hook(std::ostream &out, const completion_model &model)
{
    out << "# " << model.program << " fish completion. Generated by `"
        << model.program << " completion fish`; do not edit.\n"
        << "function __" << model.program << "_complete\n"
        << "    set -l tokens (commandline -opc)\n"
        << "    " << model.program << " __complete $tokens[2..-1] -- (commandline -ct)\n"
        << "end\n"
        << "complete -c " << model.program << " -f\n";
}

void fish_subcommands(std::ostream &out, const completion_model &model)
{
    for(const completion_verb &verb : model.verbs)
        out << "complete -c " << model.program
            << " -n '__fish_use_subcommand' -a " << detail::shell_single_quote(verb.name)
            << " -d " << detail::shell_single_quote(verb.description) << "\n";
}

void fish_flags(std::ostream &out, const completion_model &model)
{
    for(const completion_verb &verb : model.verbs)
        for(const completion_option &opt : verb.options)
        {
            out << "complete -c " << model.program << " -n "
                << detail::shell_single_quote("__fish_seen_subcommand_from " + verb.name)
                << " -l " << detail::long_option_name(opt.token);
            if(opt.takes_argument)
                out << " -r";
            out << " -d " << detail::shell_single_quote(opt.description) << "\n";
        }
}

void fish_dynamic(std::ostream &out, const completion_model &model)
{
    for(const completion_verb &verb : model.verbs)
    {
        const std::string guard = "__fish_seen_subcommand_from " + verb.name;
        if(verb.name == "completion")
            out << "complete -c " << model.program << " -n " << detail::shell_single_quote(guard)
                << " -f -a " << detail::shell_single_quote(std::string{ detail::supported_shells() }) << "\n";
        else if(has_dynamic_argument(verb))
            out << "complete -c " << model.program << " -n " << detail::shell_single_quote(guard)
                << " -f -a " << detail::shell_single_quote("(__" + model.program + "_complete)") << "\n";
    }
}

}

std::string emit_fish(const completion_model &model)
{
    std::ostringstream out;
    fish_header_and_hook(out, model);
    fish_subcommands(out, model);
    fish_flags(out, model);
    fish_dynamic(out, model);
    return out.str();
}

}
