#include "meios/completion/emitters.h"

#include "completion_detail.h"

#include <string>
#include <ostream>
#include <sstream>

namespace meios
{

namespace
{

void zsh_header(std::ostream &out, const completion_model &model)
{
    out << "#compdef " << model.program << "\n"
        << "# " << model.program << " zsh completion. Generated by `"
        << model.program << " completion zsh`; do not edit.\n";
}

void zsh_dispatch(std::ostream &out, const completion_model &model)
{
    out << "_" << model.program << "() {\n"
        << "    local -a commands\n"
        << "    commands=(\n";
    for(const completion_verb &verb : model.verbs)
        out << "        " << detail::shell_single_quote(verb.name + ":" + verb.description) << "\n";
    out << "    )\n"
        << "    local curcontext=\"${curcontext}\" state\n"
        << "    _arguments -C '1:command:->command' '*::arguments:->args'\n"
        << "    case \"${state}\" in\n"
        << "        command) _describe -t commands 'command' commands ;;\n"
        << "        args) _" << model.program << "_args ;;\n"
        << "    esac\n}\n";
}

void zsh_args_function(std::ostream &out, const completion_model &model)
{
    out << "_" << model.program << "_args() {\n"
        << "    if [[ \"${words[CURRENT]}\" == -* ]]; then\n"
        << "        _" << model.program << "_flags \"${words[1]}\"\n"
        << "        return\n"
        << "    fi\n"
        << "    if [[ \"${words[1]}\" == completion ]]; then\n"
        << "        _values 'shell' " << detail::supported_shells() << "\n"
        << "        return\n"
        << "    fi\n"
        << "    local -a candidates\n"
        << "    candidates=(\"${(@f)$(" << model.program
        << " __complete \"${words[@]:1}\" -- \"${words[CURRENT]}\")}\")\n"
        << "    _describe -t candidates 'candidate' candidates\n"
        << "}\n";
}

void zsh_flags_function(std::ostream &out, const completion_model &model)
{
    out << "_" << model.program << "_flags() {\n    case \"$1\" in\n";
    for(const completion_verb &verb : model.verbs)
    {
        out << "        " << verb.name << ") _values 'flag'";
        for(const completion_option &opt : verb.options)
            out << " " << detail::shell_single_quote(opt.token + "[" + opt.description + "]");
        out << " ;;\n";
    }
    out << "    esac\n}\n";
}

}

std::string emit_zsh(const completion_model &model)
{
    std::ostringstream out;
    zsh_header(out, model);
    zsh_dispatch(out, model);
    zsh_args_function(out, model);
    zsh_flags_function(out, model);
    out << "_" << model.program << " \"$@\"\n";
    return out.str();
}

}
