if(TARGET meios_scan-obj)
    add_executable(mesh_scan mesh_scan.cpp)
    target_link_libraries(mesh_scan PRIVATE meios::urdf meios::scan-obj)
    meios_warnings(mesh_scan)
    add_test(NAME example_mesh_scan COMMAND mesh_scan)
endif()

if(TARGET meios_scan-collada)
    add_executable(collada_scan collada_scan.cpp)
    target_link_libraries(collada_scan PRIVATE meios::io meios::scan-collada)
    meios_warnings(collada_scan)
    add_test(NAME example_collada_scan COMMAND collada_scan)
endif()

if(TARGET meios_scan-gltf)
    add_executable(gltf_scan gltf_scan.cpp)
    target_link_libraries(gltf_scan PRIVATE meios::io meios::scan-gltf)
    meios_warnings(gltf_scan)
    add_test(NAME example_gltf_scan COMMAND gltf_scan)
endif()

if(TARGET meios_scan-stl)
    add_executable(stl_scan stl_scan.cpp)
    target_link_libraries(stl_scan PRIVATE meios::io meios::bundle meios::scan-stl)
    meios_warnings(stl_scan)
    add_test(NAME example_stl_scan COMMAND stl_scan)
endif()
