#!/usr/bin/env python3
"""Takes CPython's accept-or-refuse verdict for an expression body and writes it into a test
table, plus the well-formed enumeration a before-and-after run is fed.

Needs a CPython 3 interpreter and nothing else: no virtual environment, no xacro, no PyYAML.
Writes no record under tests/golden/oracle and is never invoked from a test.
"""
import argparse
import sys

CARRIERS = [
    ("1 if True else 2 ", ""),
    ("1 if False else 2 ", ""),
    ("True or 1 ", ""),
    ("False and 1 ", ""),
    ("False or 1 ", ""),
    ("True and 1 ", ""),
    ("1 + 2 ", ""),
    ("(1 if True else 2) ", ""),
    ("max(1 if True else 2 ", ", 5)"),
]

MALFORMED_FRAGMENTS = ["3", "+", ") )", "3 4", "* * 2", "if", "'x'"]
WELLFORMED_FRAGMENTS = ["", "+ 1", "* 2", "< 3", "and True"]

OPERANDS = ["a", "b", "c", "0", "1", "True", "False"]
CHAIN_OPS = ["and", "or"]

ASSUMPTION = ("Upstream's accept-or-refuse boundary for an expression body is assumed to be\n"
              "// CPython's own; that equivalence is assumed here, not measured.")


def compiles(text):
    try:
        compile(text, "<expression>", "eval")
        return True
    except SyntaxError:
        return False


def spliced(fragments):
    return [(before + fragment + after, before, fragment)
            for before, after in CARRIERS for fragment in fragments]


def wellformed_enumeration():
    out = []
    for op in CHAIN_OPS:
        for x in OPERANDS:
            for y in OPERANDS:
                out.append(f"{x} {op} {y}")
    for op in CHAIN_OPS:
        for x in OPERANDS:
            for y in OPERANDS:
                for z in OPERANDS:
                    out.append(f"{x} {op} {y} {op} {z}")
    conditions = list(OPERANDS)
    for comparison in ["<", "!="]:
        for x in OPERANDS:
            for y in OPERANDS:
                conditions.append(f"{x} {comparison} {y}")
    conditionals = [f"{x} if {condition} else {y}"
                    for x in OPERANDS for condition in conditions for y in OPERANDS]
    out.extend(conditionals)
    out.extend(f"max({inner}, {z})" for inner in conditionals for z in OPERANDS)
    return out


def refuse(reason, offenders):
    print(f"refusal-parity: {reason}", file=sys.stderr)
    for one in offenders[:10]:
        print(f"  {one!r}", file=sys.stderr)
    raise SystemExit(1)


def gate():
    accepted = [text for text, _, _ in spliced(MALFORMED_FRAGMENTS) if compiles(text)]
    if accepted:
        refuse("a member of the malformed product compiles under CPython and is therefore not "
               "malformed; nothing written", accepted)
    rejected = [text for text, _, _ in spliced(WELLFORMED_FRAGMENTS) if not compiles(text)]
    if rejected:
        refuse("a member of the well-formed product does not compile under CPython; the fragment "
               "does not splice into every carrier, nothing written", rejected)
    enumeration = wellformed_enumeration()
    unusable = [text for text in enumeration if not compiles(text)]
    if unusable:
        refuse("a member of the well-formed enumeration does not compile under CPython; "
               "nothing written", unusable)
    return enumeration


# Upstream is what the records under tests/golden/oracle measure. This cross-check is the cheap
# part of that question the generator can answer where an xacro happens to be installed, and it
# is deliberately not a gate: most environments have no xacro and the generator must still run.
def cross_check():
    try:
        import xacro
    except ImportError:
        print("refusal-parity: no xacro importable; CPython verdicts stand unchecked",
              file=sys.stderr)
        return
    from xacro import XacroException
    disagreed = []
    for text, _, _ in spliced(MALFORMED_FRAGMENTS)[:9]:
        try:
            xacro.eval_text("${" + text + "}", {})
            disagreed.append(text)
        except (XacroException, SyntaxError, NameError, TypeError):
            pass
    print(f"refusal-parity: xacro {getattr(xacro, '__version__', 'unknown')} disagreed on "
          f"{len(disagreed)} of 9 sampled members: {disagreed}", file=sys.stderr)


def quoted(text):
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def array(name, values):
    body = ",\n    ".join(quoted(one) for one in values)
    return (f"inline constexpr std::string_view {name}[] = {{\n    {body},\n}};\n")


def table_text():
    rows = ",\n    ".join(f"carrier{{ {quoted(before)}, {quoted(after)} }}"
                          for before, after in CARRIERS)
    return f"""#ifndef HPP_GUARD_MEIOS_UNIT_SYNTAX_TABLE_H
#define HPP_GUARD_MEIOS_UNIT_SYNTAX_TABLE_H

// Generated by tests/tools/oracle/refusal_parity.py; the verdicts are {sys.version.split()[0]}'s,
// which refuses every malformed member below and accepts every well-formed one.
// {ASSUMPTION}

#include <string>
#include <string_view>

namespace syntax
{{

struct carrier
{{
    std::string_view before;
    std::string_view after;
}};

inline constexpr carrier carriers[] = {{
    {rows},
}};

{array("malformed_fragments", MALFORMED_FRAGMENTS)}
{array("wellformed_fragments", WELLFORMED_FRAGMENTS)}
inline std::string formed(const carrier &around, std::string_view fragment)
{{
    return std::string(around.before) + std::string(fragment) + std::string(around.after);
}}

}}

#endif
"""


def main():
    parsed = argparse.ArgumentParser(description=__doc__)
    parsed.add_argument("--table", required=True)
    parsed.add_argument("--cases", required=True)
    args = parsed.parse_args()
    enumeration = gate()
    cross_check()
    with open(args.table, "w", encoding="utf-8", newline="\n") as out:
        out.write(table_text())
    with open(args.cases, "w", encoding="utf-8", newline="\n") as out:
        out.write("\n".join(enumeration) + "\n")
    print(f"refusal-parity: {len(CARRIERS)} carriers, {len(MALFORMED_FRAGMENTS)} malformed and "
          f"{len(WELLFORMED_FRAGMENTS)} well-formed fragments, "
          f"{len(enumeration)} enumerated forms")


main()
