# meios bash completion. Generated by `meios completion bash`; do not edit.
# Commands:
#   flatten - Expand xacro and resolve a URDF, printing the flattened document.
#   bundle - Write a self-contained package folder with rewritten references.
#   info - Print a summary of the resolved model.
#   validate - Check the model and report diagnostics by class.
#   tree - Print the link and joint topology.
#   deps - List the assets the model references.
#   args - List the declared arguments of the document.
#   resolve - Resolve an asset reference (package://, relative, absolute or file://) to its on-disk path; a relative one is measured against the model document's directory, and an unreachable path or unsupported scheme is refused.
#   completion - Generate a shell completion script.
_meios() {
    local cur words cword
    cur="${COMP_WORDS[COMP_CWORD]}"
    words=("${COMP_WORDS[@]}")
    cword="${COMP_CWORD}"
    if [ "${cword}" -eq 1 ]; then
        COMPREPLY=($(compgen -W "flatten bundle info validate tree deps args resolve completion" -- "${cur}"))
        return
    fi
    local verb="${words[1]}"
    if [ "${verb}" = "completion" ] && [ "${cword}" -eq 2 ]; then
        COMPREPLY=($(compgen -W "bash zsh fish" -- "${cur}"))
        return
    fi
    if [ "${cur#-}" != "${cur}" ]; then
        COMPREPLY=($(compgen -W "$(_meios_flags "${verb}")" -- "${cur}"))
        return
    fi
    local candidate candidates=()
    while IFS= read -r candidate; do
        candidates+=("${candidate}")
    done < <(meios __complete "${words[@]:1:${cword}-1}" -- "${cur}")
    COMPREPLY=()
    for candidate in "${candidates[@]}"; do
        if [ -z "${cur}" ] || [ "${candidate#"${cur}"}" != "${candidate}" ]; then
            COMPREPLY+=("${candidate}")
        fi
    done
}
_meios_flags() {
    case "$1" in
        flatten) printf '%s\n' "--package-path --eval --eval-policy" ;;
        bundle) printf '%s\n' "--package-path --name" ;;
        info) printf '%s\n' "--package-path --format" ;;
        validate) printf '%s\n' "--package-path --format" ;;
        tree) printf '%s\n' "--package-path --dot --root" ;;
        deps) printf '%s\n' "--package-path --eval --eval-policy" ;;
        args) printf '%s\n' "--package-path" ;;
        resolve) printf '%s\n' "--package-path" ;;
        completion) printf '%s\n' "" ;;
    esac
}
complete -F _meios meios
