#compdef meios
# meios zsh completion. Generated by `meios completion zsh`; do not edit.
_meios() {
    local -a commands
    commands=(
        'flatten:Expand xacro and resolve a URDF, printing the flattened document.'
        'bundle:Write a self-contained package folder with rewritten references.'
        'info:Print a summary of the resolved model.'
        'validate:Check the model and report diagnostics by class.'
        'tree:Print the link and joint topology.'
        'deps:List the assets the model references.'
        'args:List the declared arguments of the document.'
        'resolve:Resolve an asset reference (package://, relative, absolute or file://) to its on-disk path; a relative one is measured against the model document'\''s directory, and an unreachable path or unsupported scheme is refused.'
        'completion:Generate a shell completion script.'
    )
    local curcontext="${curcontext}" state
    _arguments -C '1:command:->command' '*::arguments:->args'
    case "${state}" in
        command) _describe -t commands 'command' commands ;;
        args) _meios_args ;;
    esac
}
_meios_args() {
    if [[ "${words[CURRENT]}" == -* ]]; then
        _meios_flags "${words[1]}"
        return
    fi
    if [[ "${words[1]}" == completion ]]; then
        _values 'shell' bash zsh fish
        return
    fi
    local -a candidates
    candidates=("${(@f)$(meios __complete "${words[@]:1}" -- "${words[CURRENT]}")}")
    _describe -t candidates 'candidate' candidates
}
_meios_flags() {
    case "$1" in
        flatten) _values 'flag' '--package-path[Additional package search root, repeatable.]' '--eval[Expression evaluator backend: core or python.]' '--eval-policy[Policy for an unsupported expression: fail, warn, or skip.]' ;;
        bundle) _values 'flag' '--package-path[Additional package search root, repeatable.]' '--name[Name of the emitted bundle package.]' ;;
        info) _values 'flag' '--package-path[Additional package search root, repeatable.]' '--format[Output format for the summary.]' ;;
        validate) _values 'flag' '--package-path[Additional package search root, repeatable.]' '--format[Output format for the report.]' ;;
        tree) _values 'flag' '--package-path[Additional package search root, repeatable.]' '--dot[Emit Graphviz DOT instead of ASCII.]' '--root[Render the subtree rooted at this link.]' ;;
        deps) _values 'flag' '--package-path[Additional package search root, repeatable.]' '--eval[Expression evaluator backend: core or python.]' '--eval-policy[Policy for an unsupported expression: fail, warn, or skip.]' ;;
        args) _values 'flag' '--package-path[Additional package search root, repeatable.]' ;;
        resolve) _values 'flag' '--package-path[Additional package search root, repeatable.]' ;;
        completion) _values 'flag' ;;
    esac
}
_meios "$@"
