#ifndef HPP_GUARD_MEIOS_UNIT_SYNTAX_TABLE_H
#define HPP_GUARD_MEIOS_UNIT_SYNTAX_TABLE_H

// Generated by tests/tools/oracle/refusal_parity.py; the verdicts are 3.14.6's,
// which refuses every malformed member below and accepts every well-formed one.
// Upstream's accept-or-refuse boundary for an expression body is assumed to be
// CPython's own; that equivalence is assumed here, not measured.

#include <string>
#include <string_view>

namespace syntax
{

struct carrier
{
    std::string_view before;
    std::string_view after;
};

inline constexpr carrier carriers[] = {
    carrier{ "1 if True else 2 ", "" },
    carrier{ "1 if False else 2 ", "" },
    carrier{ "True or 1 ", "" },
    carrier{ "False and 1 ", "" },
    carrier{ "False or 1 ", "" },
    carrier{ "True and 1 ", "" },
    carrier{ "1 + 2 ", "" },
    carrier{ "(1 if True else 2) ", "" },
    carrier{ "max(1 if True else 2 ", ", 5)" },
};

inline constexpr std::string_view malformed_fragments[] = {
    "3",
    "+",
    ") )",
    "3 4",
    "* * 2",
    "if",
    "'x'",
};

inline constexpr std::string_view wellformed_fragments[] = {
    "",
    "+ 1",
    "* 2",
    "< 3",
    "and True",
};

inline std::string formed(const carrier &around, std::string_view fragment)
{
    return std::string(around.before) + std::string(fragment) + std::string(around.after);
}

}

#endif
